const data = {
  products: [
    {
      name: 'Harry Potter',
      slug: 'harry-potter',
      category: 'Children',
      image: '/images/p1.jpeg', // 170px × 259px
      price: 120,
      countInStock: 10,
      brand: 'Arthur',
      rating: 4.5,
      numReviews: 10,
      description: 'SF',
    },
    {
      name: 'Warriors',
      slug: 'warriors',
      category: 'Children',
      image: '/images/p2.jpeg',
      price: 250,
      countInStock: 20,
      brand: 'Arthur',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'The Little Prince',
      slug: 'the-little-prince',
      category: 'Children',
      image: '/images/p3.jpeg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Pride and Prejudice',
      slug: 'pride-and-prejudice',
      category: 'Pants',
      image: '/images/p4.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
  ],
};
export default data;
